services:

  php:
    image: php:apache
    container_name: phpApache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql
    container_name: MySQL
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ''

volumes:
  mysql_data:
