services:
  phpApache:
    image: php:apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  MySQL:
    image: mysql
    volumes:
      - ambiente_padrao_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  phpMyAdmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: MySQL
      MYSQL_ROOT_PASSWORD: ''

volumes:
  ambiente_padrao_mysql_data:
    external: true
