services:

  phpApache:
    image: php-mysqli-ativo
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  MySQL:
    image: mysql
    restart: always
    volumes:
      - C:\dev\ambiente_padrao\my_dados:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  phpMyAdmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ''
